---
# ALL CONFIGURATIONS FOR SSH GOES IN HERE

- name: Check .ssh directory exists
  stat:
    path: "{{ server_home }}/.ssh"
  register: "stat_result"

- name: Install openssh server
  when: ansible_distribution == "Ubuntu"
  apt:
    pkg: "openssh-server"
    state: "present"
    install_recommends: "yes"
  notify: "Start openssh service"
