---
- name: Prepare
  hosts: all
  become: "yes"
  tasks:
    - name: Copy dns config box
      copy:
        src: "01-netcfg.yaml"
        dest: "/etc/netplan/01-netcfg.yaml"
        mode: "0744"
      register: "result"
    - name: Apply dns config
      when: "result is succeeded"
      shell: "netplan apply && echo SUCCESS"
    - name: Print env variable
      debug:
        msg: "'{{ lookup('env', 'PKR_VAR_secret_id')}}'"
